feat: Implement delete site action menu - EXO-64952 - Meeds-io/MIPs#68
exoplatform/layout-management pull request #158
Opened 2023-07-03 09:54 UTC by GouadriaHanen

2023-07-05 15:03 UTC, azayati requested changes

2023-07-05 15:03 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteManagementRestService.java
> +  @Operation(summary = "removed sites", method = "GET", description = "This removes sites")
```suggestion
  @Operation(summary = "Delete a site", method = "GET", description = "This deletes the given site")
```

2023-07-05 15:03 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteManagementRestService.java
> +      LOG.error("Error when removing sites", e);
```suggestion
      LOG.error("Error when deleting the site with name {} and type {}", siteName, siteType, e);
```

2023-07-05 15:03 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-management/siteManagementService.js
> +      throw new Error('Error when deleting sites');
```suggestion
      throw new Error('Error when deleting site');
```

2023-07-05 15:10 UTC, azayati requested changes

2023-07-05 15:10 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteManagementRestService.java
> +import javax.ws.rs.*;
```suggestion
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
```

2023-07-06 12:56 UTC, azayati requested changes

2023-07-06 12:56 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteManagementRestService.java
> +  @Operation(summary = "removed sites", method = "GET", description = "This removes sites")
to be considered @GouadriaHanen

2023-07-06 13:00 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-07-06 13:06 UTC, azayati approved these changes
LGTM

2023-07-06 13:36 UTC, merged