feat: Add images portlet permissions to change images - EXO-65944 - Meeds-io/MIPs#68
exoplatform/layout-management pull request #214
Opened 2023-08-25 11:50 UTC by IlhemEssaadi

2023-08-25 17:22 UTC, azayati requested changes
we should add the portlet in the needed category

2023-08-31 12:02 UTC, azayati requested changes

2023-08-31 12:02 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/ImageRestService.java
> +  @Path("isPublisher")
Instead I suggest to add this information canChange or canEdit into the ImageRestEntity.
This will avoid to do additional HTTP Requests for every portlet instance in the same page.

2023-08-31 15:13 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-08-31 18:18 UTC, azayati approved these changes
LGTM

2023-08-31 18:18 UTC, merged