feat: Add Icon Picker font awesome component - EXO-65005 - Meeds-io/MIPs#72
exoplatform/layout-management pull request #237
Opened 2023-09-18 08:40 UTC by IlhemEssaadi

2023-09-18 15:47 UTC, azayati requested changes

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNodeDrawer.vue
>                    :title="$t('siteNavigation.btn.deleteIcon.title')"
we should have the title displayed like for visibility info case, same for changeIcon case

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigation.vue
> +    <font-awesome-picker-drawer />
```suggestion
    <font-awesome-picker-drawer v-if="siteNavigationDrawerOpened" />
```

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteNavigationPortlet_en.properties
> +siteNavigation.label.selectIcon.title=Select Icon
```suggestion
siteNavigation.fontAwesomePickerDrawer.title=Select Icon
```

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteNavigationPortlet_en.properties
> +siteNavigation.label.btn.showMore=show More
```suggestion
siteNavigation.btn.showMore.title=Show More
```

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/package.json
> +    "@fortawesome/free-solid-svg-icons": "^5.7.1"
```suggestion
    "@fortawesome/fontawesome-svg-core": "^1.2.36",
    "@fortawesome/free-solid-svg-icons": "^5.15.4"
```

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/FontAwesomePickerDrawer.vue
> +<!--
Rename to NodeIconPickerDrawer.vue

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/FontAwesomePickerDrawer.vue
> +    id="fontAwesomePickerDrawer"
```suggestion
    ref="nodeIconPickerDrawer"
    id="nodeIconPickerDrawer"
```

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/FontAwesomePickerDrawer.vue
> +          placeholder="filter by name"
add an internationalized label

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/FontAwesomePickerDrawer.vue
> +                :class="selectedIcon === icon ? 'grey-background' : 'light-grey-background'"
computed

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/FontAwesomePickerDrawer.vue
> +import { fas } from '@fortawesome/free-solid-svg-icons';
no imports allowed directly in vuejs files:
https://github.com/Meeds-io/meeds/blob/develop/CODING_GUIDELINES.md#devstd-29

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/FontAwesomePickerDrawer.vue
> +    this.$root.$on('open-font-awesome-picker-drawer', this.open);
```suggestion
    this.$root.$on('open-node-icon-picker-drawer', this.open);
```

2023-09-18 15:47 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNodeDrawer.vue
> +    this.$root.$on('update-icon-node', (icon) => {
```suggestion
    this.$root.$on('update-node-icon', (icon) => {
```

2023-09-19 14:12 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-19 15:03 UTC, azayati requested changes
+
https://github.com/exoplatform/layout-management/pull/237/files#r1328854141

2023-09-19 15:03 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeIconPickerDrawer.vue
> +  data () {
```suggestion
  data() {
```

2023-09-19 15:03 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeIconPickerDrawer.vue
> +    filterIcons (event) {
```suggestion
    filterIcons(event) {
```

2023-09-19 15:05 UTC, azayati requested changes

2023-09-19 15:05 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteNavigationPortlet_en.properties
> +siteNavigation.fontAwesomePickerDrawer.title=Select Icon
```suggestion
siteNavigation.nodeIconPickerDrawer.title=Select Icon
```

2023-09-19 15:05 UTC, azayati commented on layout-management-webapps/src/main/webapp/skin/less/siteNavigation.less
> +#fontAwesomePickerDrawer {
```suggestion
#nodeIconPickerDrawer {
```

2023-09-19 15:05 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNodeDrawer.vue
> +                  @click="openFontAwesomePicker">
```suggestion
                  @click="openNodeIconPickerDrawer">
```

2023-09-20 17:08 UTC, azayati approved these changes
LGTM

2023-09-20 17:08 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeIconPickerDrawer.vue
> +      this.allIcons =this.fontLibrary.icons.map(icon => ({
```suggestion
      this.allIcons = this.fontLibrary.icons.map(icon => ({
```

2023-09-20 17:11 UTC, merged