fix: Implement create site - EXO-67615
exoplatform/layout-management pull request #280
Opened 2023-12-11 08:39 UTC by GouadriaHanen

2023-12-11 10:52 UTC, ahamdi submitted a review, later dismissed
This is not a bug and should not be integrated in the TC fixes. This is clearly an improvement /new feature.
cc @rdenarie @azayati @Jihed525

2023-12-12 13:44 UTC, azayati requested changes

2023-12-12 13:44 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteManagementRestService.java
> +                               String lang) {
add a dedicated site rest entity

2023-12-12 13:44 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteManagementRestService.java
> +            LOG.error("Error when crating the site with name {} and type {}", siteName, e);
```suggestion
            LOG.error("Error when creating the site with name {} and type {}", siteName, e);
```

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteManagementPortlet_en.properties
> +siteManagement.label.template.mandatory=The template is missing, it mandatory for creating site
```suggestion
siteManagement.label.template.mandatory=The template is missing, it is mandatory for creating site
```

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/conf/portal/portal/template/navigationWebsite/portal.xml
> +  xsi:schemaLocation="http://www.gatein.org/xml/ns/gatein_objects_1_10 http://www.gatein.org/xml/ns/gatein_objects_1_10"
use 1_11 instead of 1_10

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/conf/portal/portal/template/navigationWebsite/pages.xml
> +  xsi:schemaLocation="http://www.gatein.org/xml/ns/gatein_objects_1_8 http://www.gatein.org/xml/ns/gatein_objects_1_8"
use 1_11 instead of 1_8

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/conf/portal/portal/template/navigationWebsite/navigation.xml
> +  xsi:schemaLocation="http://www.gatein.org/xml/ns/gatein_objects_1_6 http://www.gatein.org/xml/ns/gatein_objects_1_6"
use 1_11 instead of 1_6

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/conf/portal/portal/template/navigationWebsite/portal.xml
> +          <page-body> </page-body>
```suggestion
          <page-body />
```

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/webapp/skin/less/site/Style.less
> +*/
wrong header

2023-12-12 13:44 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/gatein-resources.xml
> +    <skin-module>commonLayoutComponents</skin-module>
change the skin module name

2023-12-13 11:38 UTC, azayati requested changes

2023-12-13 11:38 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/gatein-resources.xml
> +    <css-path>/skin/css/site/Style.css</css-path>
```suggestion
    <css-path>/skin/css/navigationWebsiteLayout.css</css-path>
```

2023-12-13 11:42 UTC, azayati approved these changes
LGTM

2023-12-13 11:46 UTC, merged