fix: Add site navigation extension in a load-group - EXO-68206
exoplatform/layout-management pull request #299
Opened 2023-12-22 07:56 UTC by IlhemEssaadi

2023-12-22 16:14 UTC, azayati requested changes
Do you need changes on .vue files regarding styles in [this commit](https://github.com/exoplatform/layout-management/commit/d51021110bf2501b0640466bd93a34e65cc9a894)

2023-12-22 16:14 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/main.js
> +extensionRegistry.registerComponent('buttonManageSpaceActions', 'button-manage-space-actions', {
```suggestion
extensionRegistry.registerComponent('manageSpaceActions', 'manage-space-actions', {
```

2023-12-22 16:14 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/main.js
> +extensionRegistry.registerComponent('drawersManageSpaceActions', 'drawers-manage-space-actions', {
```suggestion
extensionRegistry.registerComponent('manageSpaceActionsDrawers', 'manage-space-drawers', {
```

2023-12-22 18:41 UTC, azayati requested changes, later dismissed

2023-12-22 18:41 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/main.js
> +extensionRegistry.registerComponent('manageSpaceDrawer', 'manage-space-drawers', {
```suggestion
extensionRegistry.registerComponent('manageSpaceDrawers', 'manage-space-drawers', {
```

2023-12-22 18:52 UTC, IlhemEssaadi commented
> Do you need changes on .vue files regarding styles in [this commit](https://github.com/exoplatform/layout-management/commit/d51021110bf2501b0640466bd93a34e65cc9a894)

No, I don't need to make changes for styles.

2023-12-22 21:50 UTC, azayati commented
> > Do you need changes on .vue files regarding styles in [this commit](https://github.com/exoplatform/layout-management/commit/d51021110bf2501b0640466bd93a34e65cc9a894)
> 
> No, I don't need to make changes for styles.

Ok so you need to revert the changes in the previous commit @IlhemEssaadi ?

2023-12-25 09:02 UTC, IlhemEssaadi commented
> > > Do you need changes on .vue files regarding styles in [this commit](https://github.com/exoplatform/layout-management/commit/d51021110bf2501b0640466bd93a34e65cc9a894)
> > 
> > 
> > No, I don't need to make changes for styles.
> 
> Ok so you need to revert the changes of styles done in the previous commit @IlhemEssaadi ?

I still need the changes made in the previous commit.

2023-12-26 12:10 UTC, ahamdi requested changes

2023-12-26 12:10 UTC, ahamdi commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationDrawersActions.vue
> +  </div>
Could we have the v-if in a single place instead of duplicating it 4 times ?

2023-12-26 14:48 UTC, ahamdi approved these changes

2023-12-26 16:15 UTC, ahamdi approved these changes

2023-12-26 17:31 UTC, merged