feat: Implement the delete node action - EXO-63071 - Meeds-io/meeds#51
exoplatform/layout-management pull request #34
Opened 2023-03-31 08:03 UTC by IlhemEssaadi

2023-03-31 12:58 UTC, azayati requested changes

2023-03-31 12:58 UTC, azayati commented on pom.xml
> +    </modules>
format code

2023-03-31 12:58 UTC, azayati commented on layout-management-webapps/src/main/webapp/WEB-INF/conf/layout-management/layout-management-configuration.xml
> +    <component>
put the configuration of service layer in resources\conf\portal\configuration.xml of layout-management-services module

2023-03-31 12:58 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/service/LayoutManagementServiceImpl.java
> +  public void removeNode(Long nodeId) {
We need to check if this can be declared and implemented directly into NavigationService layer of gatein-portal

2023-03-31 12:58 UTC, azayati commented on layout-management-services/pom.xml
> +      </plugin>
To start we add only needed plugins, remove the unneeded one then we can add others if needed

2023-03-31 12:58 UTC, azayati commented on layout-management-services/pom.xml
> +    <dependency>
keep only exact needed dependencies

2023-03-31 12:58 UTC, azayati commented on layout-management-api/src/main/java/org/exoplatform/layoutmanagement/service/LayoutManagementService.java
> +public interface LayoutManagementService {
We need to check if this can be declared and implemented directly into NavigationService layer of gatein-portal

2023-03-31 12:58 UTC, azayati commented on layout-management-api/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
we should check if api module is needed since we can probably call directly gatein-portal service api layer from layout management rest services

2023-04-03 08:37 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-04-03 09:32 UTC, azayati requested changes

2023-04-03 09:32 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/LayoutManagementRest.java
> +package org.exoplatform.layoutmanagement.rest;
Rename the class SiteNavigationRestService.java

2023-04-03 09:32 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/LayoutManagementRest.java
> +@Path("v1/layoutManagement")
```suggestion
@Path("v1/siteNavigation")
```

2023-04-03 09:32 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/LayoutManagementRest.java
> +  @Path("{nodeId}")
```suggestion
  @Path("{/node/nodeId}")
```

2023-04-03 09:32 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/LayoutManagementRest.java
> +  public Response removeNode(@Context
```suggestion
  public Response deleteNode(@Context
```

2023-04-03 09:32 UTC, azayati commented on layout-management-services/pom.xml
> +      <artifactId>commons-component-common</artifactId>
do we need this dependency ?

2023-04-03 09:32 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/LayoutManagementRest.java
> +package org.exoplatform.layoutmanagement.rest;
add license header

2023-04-03 09:32 UTC, azayati commented on layout-management-services/src/main/resources/conf/portal/configuration.xml
> +-->
update the right license header

2023-04-04 10:20 UTC, azayati requested changes

2023-04-04 10:20 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +  @Operation(summary = "Delete Node ", method = "DELETE", description = "This deletes the node")
```suggestion
  @Operation(summary = "Delete Node ", method = "DELETE", description = "This deletes the navigation node")
```

2023-04-04 10:20 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +    org.exoplatform.services.security.Identity currentIdentity = ConversationState.getCurrent().getIdentity();
you can add the import above and use Identity only here

2023-04-04 10:20 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +      LOG.error("Error when deleting the node with id " + nodeId, e);
```suggestion
      LOG.error("Error when deleting the navigation node with id {}", nodeId, e);
```

2023-04-04 10:20 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +    org.exoplatform.services.security.Identity currentIdentity = ConversationState.getCurrent().getIdentity();
we should check that the user has the permission to delete the node

2023-04-04 10:20 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +                                 Long nodeId) {
we should check that the user has the permission to undo delete the node

2023-04-04 10:20 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +                     .entity("Node with id {} was already deleted or isn't planned to be deleted" + nodeId)
```suggestion
                     .entity("Node with id {} was already deleted or isn't planned to be deleted", nodeId)
```

2023-04-04 10:20 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/initComponents.js
> +import ExoNavigationNodeNotificationAlerts from './snackbar/ExoNavigationNodeNotificationAlerts.vue';
```suggestion
import SiteNavigationNotificationAlert from './snackbar/SiteNavigationNotificationAlert.vue';
import SiteNavigationNotificationAlerts from './snackbar/SiteNavigationNotificationAlerts.vue';
```

2023-04-04 10:20 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/initComponents.js
> +  'exo-navigation-node-notification-alerts': ExoNavigationNodeNotificationAlerts,
```suggestion
  'site-navigation-notification-alert': SiteNavigationNotificationAlert,
  'site-navigation-notification-alerts': SiteNavigationNotificationAlerts,
```

2023-04-04 10:20 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/main.js
>  import './initComponents.js';
revert this change

2023-04-04 10:20 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/siteNavigationService.js
> +      throw new Error('Error when deleting node');
```suggestion
      throw new Error('Error when deleting navigation node');
```

2023-04-04 10:20 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/siteNavigationService.js
> +      throw new Error('Error when undoing deleting node');
```suggestion
      throw new Error('Error when undoing deleting navigation ode');
```

2023-04-04 15:33 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-04-04 18:21 UTC, azayati approved these changes
LGTM

2023-04-04 18:21 UTC, merged