feat: Implement move up and move down actions - EXO-63074
exoplatform/layout-management pull request #47
Opened 2023-04-07 07:58 UTC by IlhemEssaadi

2023-04-07 14:07 UTC, azayati requested changes

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +  @PUT
```suggestion
  @PATCH
```
since we will not update the entire entity

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +        return Response.status(Response.Status.BAD_REQUEST).entity("either_nodeId_or_previousId_is_mandatory").build();
```suggestion
        return Response.status(Response.Status.BAD_REQUEST).entity("Node id and previous node id are mandatory").build();
```

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +          @ApiResponse(responseCode = "403", description = "Unauthorized operation"),
```suggestion
          @ApiResponse(responseCode = "401", description = "User not authorized to move the navigation node"),
```

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +          @ApiResponse(responseCode = "404", description = "Resource not found")})
```suggestion
          @ApiResponse(responseCode = "404", description = "Node not found")})
```

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +      navigationService.moveNode(nodeId, parentId, parentId, previousId);
```suggestion
      navigationService.moveNode(nodeId, parentId, parentId, previousNodeId);
```

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +      Long parentId = Long.valueOf(nodeData.getParentId());
```suggestion
      long parentId = Long.valueOf(nodeData.getParentId());
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +    canMoveUpChildNode(navigationNode){
```suggestion
    canMoveUpChildNode(navigationNode) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +    canMoveDownChildNode(navigationNode){
```suggestion
    canMoveDownChildNode(navigationNode) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +    moveUpChildNode(navigationNodeId){
```suggestion
    moveUpChildNode(navigationNodeId) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +        if (index !== -1){
```suggestion
        if (index !== -1) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +          const previousId = index > 1 ? this.navigationNode.children[index-2].id :null;
```suggestion
          const previousNodeId = index > 1 ? this.navigationNode.children[index - 2].id : null;
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +    moveDownChildNode(navigationNodeId){
```suggestion
    moveDownChildNode(navigationNodeId) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +        if (index !== -1){
```suggestion
        if (index !== -1) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodeItem.vue
> +          const previousId = this.navigationNode.children[index+1].id;
```suggestion
          const previousNodeId = this.navigationNode.children[index + 1].id;
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodesList.vue
> +    canMoveUpNode(navigationNode){
```suggestion
    canMoveUpNode(navigationNode) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodesList.vue
> +    canMoveDownNode(navigationNode){
```suggestion
    canMoveDownNode(navigationNode) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodesList.vue
> +    moveUpNode(navigationNodeId){
```suggestion
    moveUpNode(navigationNodeId) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodesList.vue
> +          const previousId = index >1 ? this.navigationNodes[index-2].id : null;
```suggestion
        if (index !== -1) {
          const previousNodeId = index > 1 ? this.navigationNodes[index - 2].id : null;
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodesList.vue
> +    moveDownNode(navigationNodeId){
```suggestion
    moveDownNode(navigationNodeId) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/NodesList.vue
> +        if (index !== -1){
```suggestion
        if (index !== -1) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/siteNavigationService.js
> +export function moveNode(nodeId, previousId) {
```suggestion
export function moveNode(nodeId, previousNodeId) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +                            @Parameter(description = "previous id") @QueryParam("previousId") Long previousId) {
```suggestion
                            @Parameter(description = "previous id") @QueryParam("previousId") Long previousNodeId) {
```

2023-04-07 14:07 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/siteNavigationService.js
> +    formData.append('previousId', previousId);
```suggestion
    formData.append('previousNodeId', previousNodeId);
```

2023-04-07 15:07 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-04-11 10:10 UTC, azayati approved these changes
LGTM

2023-04-11 10:10 UTC, merged