feat: Implement add node drawer - EXO-63070
exoplatform/layout-management pull request #49
Opened 2023-04-11 07:45 UTC by IlhemEssaadi

this change is to implement the add node drawer

2023-04-11 13:47 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-04-12 09:30 UTC, azayati requested changes

2023-04-12 09:30 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteNavigationPortlet_en.properties
> +siteNavigation.label.nodeLabel.title=Node Label
```suggestion
siteNavigation.label.nodeLabel.title=Node label
```

2023-04-12 09:30 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteNavigationPortlet_en.properties
> +siteNavigation.label.addNode.title=Add node
```suggestion
siteNavigation.drawer.addNode.title=Add node
```

2023-04-12 09:30 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationAddNodeDrawer.vue
> +        return !(value && value.length) || 'Field is required.';
'Field is required' should be internationalized

2023-04-12 12:46 UTC, azayati approved these changes
LGTM

2023-04-12 12:46 UTC, merged