feat: Add New page element node - EXO-63252 - Meeds-io/MIPs#51
exoplatform/layout-management pull request #67
Opened 2023-04-17 09:58 UTC by GouadriaHanen

this change is to implement add new page element node

2023-04-18 14:00 UTC, azayati requested changes

2023-04-18 14:00 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +    pageTemplates() {
pageTemplates should be retrived dynamically like it is the case now in create page webui wizard

2023-04-18 14:00 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +      case 'analytics': return '/layout-management/images/AnalyticsPageSkeleton.png';
we should use the same images contents used in the page creation webui wizard:

- https://experience-ft.exoplatform.org/eXoSkin/skin/images/themes/default/Container/default-layout.png
- https://experience-ft.exoplatform.org/eXoSkin/skin/images/themes/default/Container/ItemSelector.png
- https://github.com/Meeds-io/analytics/blob/develop/analytics-webapps/src/main/webapp/skin/images/analytics-layout.png

2023-04-18 14:00 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +    }
not needed IMO

2023-04-18 14:00 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationPageElement.vue
> +
useless empty lines to be removed

2023-04-19 12:45 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-04-19 13:49 UTC, azayati requested changes

2023-04-19 13:49 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +          this.pageTemplates = pageTemplates[0]?.selectItemOptions || [];
we should retrieve all page templates for all categories not only the first one

2023-04-19 13:51 UTC, azayati requested changes

2023-04-19 13:51 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +    getPageTemplates(){
```suggestion
    getPageTemplates() {
```

2023-04-19 13:51 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationPageElement.vue
> +<template>
add header

2023-04-19 13:51 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/siteNavigationService.js
> +export function getPageTemplateCategories() {
can you retrieve directly page templates from the rest service and not page templats categories ?

2023-04-19 13:51 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +<template>
add header

2023-04-24 13:32 UTC, azayati requested changes

2023-04-24 13:32 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +    <v-select
normally we should retrieve the internationalized labels dynamically from the rest service to avoid adding them statically here

2023-04-26 11:40 UTC, azayati requested changes

2023-04-26 11:40 UTC, azayati commented on layout-management-webapps/src/main/resources/locale/portlet/layoutManagement/SiteNavigationPortlet_en.properties
> +siteNavigation.label.analytics=Analytics
IMO no need to add page templates labels statically here since they should be retrieved dynamically from the rest service

2023-04-26 14:31 UTC, azayati requested changes

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +  @Operation(summary = "retrieves page template categories", method = "GET", description = "retrieves page template categories")
```suggestion
  @Operation(summary = "retrieves page templates", method = "GET", description = "retrieves page templates")
```

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +      LOG.error("Error when retrieving page template categories", e);
```suggestion
      LOG.error("Error when retrieving page templates", e);
```

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/model/PageTemplateRestEntity.java
> +  private String  skeleton;
IMO we can add only needed attributes to be used in frontend

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/model/PageTemplateRestEntity.java
> +import lombok.*;
replace with exact imports not *

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/SiteNavigationRestService.java
> +import javax.ws.rs.*;
replace with exact imports not *

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/EntityBuilder.java
> +import static org.exoplatform.layoutmanagement.utils.SiteNavigationUtils.getPageTemplateDefaultSkeleton;
import just SiteNavigationUtils and use SiteNavigationUtils.getI18NMessage and SiteNavigationUtils.getPageTemplateDefaultSkeleton below
```suggestion
import static org.exoplatform.layoutmanagement.utils.SiteNavigationUtils.getI18NMessage;
import static org.exoplatform.layoutmanagement.utils.SiteNavigationUtils.getPageTemplateDefaultSkeleton;
```

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/utils/SiteNavigationUtils.java
> +  public static String getI18NMessage(Locale userLocale, String messageKey) {
```suggestion
  public static String getI18NLabel(Locale userLocale, String label) {
```

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/utils/SiteNavigationUtils.java
> +    try {
try/catch not needed IMO

2023-04-26 14:31 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/utils/SiteNavigationUtils.java
> +  public static String getPageTemplateDefaultSkeleton(String templateName) {
```suggestion
  public static String getPageTemplateSkeleton(String templateName) {
```

2023-04-27 11:04 UTC, azayati requested changes

2023-04-27 11:04 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/siteNavigationService.js
> +      throw new Error('Error when retrieving page template categories');
```suggestion
      throw new Error('Error when retrieving page templates');
```

2023-04-27 11:04 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationNewPageElement.vue
> +      :src="`/layout-management/images/${pageTemplate}.png`"
put this value as computed
```suggestion
      :src="`/layout-management/images/page-templates/${pageTemplate}.png`"
```

2023-04-27 11:04 UTC, azayati commented on layout-management-webapps/src/main/webapp/images/analytics.png
layout-management-webapps/src/main/webapp/images/page-templates/analytics.png

2023-04-27 11:04 UTC, azayati commented on layout-management-services/src/main/java/org/exoplatform/layoutmanagement/rest/model/PageTemplateRestEntity.java
> +  private boolean selected = false;
not needed IMO

2023-04-27 11:15 UTC, azayati approved these changes
LGTM

2023-04-27 11:15 UTC, merged