feat: Implement edit node drawer - EXO-63440 - Meeds-io/meeds#51
exoplatform/layout-management pull request #86
Opened 2023-05-03 08:33 UTC by IlhemEssaadi

2023-05-03 11:52 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-05-03 14:38 UTC, azayati requested changes

2023-05-03 14:38 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationAddNodeDrawer.vue
>            @click="close()">
should we rename it now SiteNavigationNodeDrawer.vue instead ?

2023-05-03 14:38 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationAddNodeDrawer.vue
> +      return this.editMode ? this.nodeType === 'pageOrLink' && !this.navigationNode.pageKey : this.nodeType === 'pageOrLink';
why we have modified the condition ?

2023-05-03 14:38 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationAddNodeDrawer.vue
> +    this.$root.$on('open-site-navigation-add-node-drawer',this.open);
```suggestion
    this.$root.$on('open-site-navigation-add-node-drawer', this.open);
```

2023-05-03 14:38 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationAddNodeDrawer.vue
> +    this.$root.$on('open-site-navigation-edit-node-drawer',(navigationNode) => {
```suggestion
    this.$root.$on('open-site-navigation-edit-node-drawer', navigationNode => {
```

2023-05-03 14:38 UTC, azayati commented on layout-management-webapps/src/main/webapp/vue-app/site-navigation/components/SiteNavigationAddNodeDrawer.vue
>      createNode() {
I thnink that we should rename it saveNode since it is dedicated for create and edit

2023-05-04 15:27 UTC, azayati approved these changes
LGTM

2023-05-04 15:35 UTC, merged